version: 0.1.{build}

image: Visual Studio 2022

only_commits:
  files:
    - src/*

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

configuration: Debug

build:
  publish_nuget: false

before_build:
  - dotnet restore ".\src\TvMaze.Api.Client.sln"

build_script:
  - dotnet build ".\src\TvMaze.Api.Client.sln"

test_script:
  - dotnet test ".\src\TvMaze.Api.Client.Tests\TvMaze.Api.Client.Tests.csproj"

nuget:
  disable_publish_on_pr: true

for:
  - branches:
      only:
        - master

    configuration: Release

    build:
      publish_nuget: false

    after_build:
      - dotnet pack .\src\TvMaze.Api.Client\TvMaze.Api.Client.csproj -c Release -o .\artifacts --include-symbols -p:SymbolPackageFormat=snupkg

    artifacts:
      - path: '**\*.nupkg'
      - path: '**\*.snupkg'

    deploy:
      - provider: NuGet
        api_key:
          secure: N8LcRt4KOHLKIuIGvJmTeT/uzT/dnDlLAZ29mUl36cxS3VYRM+DlS3hRwYTAaU+w
        skip_symbols: false
        artifact: /.*(\.|\.s)nupkg/
